\NeedsTeXFormat{LaTeX2e} % Impide usar pdflatex (es malo)
\ProvidesClass{style}%[2022/05/01 style class]
\LoadClass[11pt]{article}
\RequirePackage{fullpage}
\RequirePackage[spanish, es-noshorthands]{babel}
\RequirePackage[letterpaper, left=3cm, right=3cm,top=2.5cm,bottom=2.5cm,margin=2cm]{geometry}
\selectlanguage{spanish}


%% include "layout/package.cls"


%% include "layout/config.cls"


%% include "layout/command.cls"


%% include "layout/listings.cls"

